/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

public class App {

    public static void main(String[] args) throws IOException {
        Bitmap bm = new Bitmap(args[0], args[1], args[2], args[3]);
    }

}
